# application.yml

spring:
  application:
    name: payment-gateway

  profiles:
    active: local

server:
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO